apiVersion: v1
kind: Service
metadata:
  name: {{ include "nginx.name" . }}
  labels:
    app.kubernetes.io/name: {{ include "nginx.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/version: {{ include "nginx.version" . }}
    environment: {{ include "nginx.environment" . }}
    product: {{ .Values.product }}
    helm.sh/chart: {{ include "nginx.chart" . }}
  annotations:
{{ toYaml .Values.service.annotations | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  {{ if .Values.whitelist.enabled -}}
  loadBalancerSourceRanges:
    {{- range .Values.whitelist.networks}}
    - {{ . }}
    {{- end }}
  {{- end }}  
  ports:
  {{- range .Values.ports }}
  - name: {{ .name }}
    port: {{ .port }}
    targetPort: {{ .port }}
    protocol: TCP
  {{- end}}
  selector:
    app.kubernetes.io/name: {{ include "nginx.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    environment: {{ include "nginx.environment" . }}
    product: {{ .Values.product }}